apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-ui
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-ui
  template:
    metadata:
      labels:
        app: registry-ui
    spec:
      containers:
        - name: registry-ui
          image: joxit/docker-registry-ui:latest
          ports:
            - containerPort: 80
          env:
            - name: REGISTRY_TITLE
              value: "Homelab Registry"
            - name: NGINX_PROXY_PASS_URL
              value: "http://registry:5000"
            - name: DELETE_IMAGES
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: registry-ui
  namespace: registry
spec:
  selector:
    app: registry-ui
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30501
  type: NodePort